PREFIX cause: <http://www.hazop2rdf.de/hazop/predicate/cause>
PREFIX consequence: <http://www.hazop2rdf.de/hazop/predicate/consequence>
PREFIX description: <http://www.hazop2rdf.de/hazop/predicate/description>
PREFIX deviation: <http://www.hazop2rdf.de/hazop/predicate/deviation>
PREFIX frequencyofpresence: <http://www.hazop2rdf.de/hazop/predicate/frequencyofpresence>
PREFIX guideword: <http://www.hazop2rdf.de/hazop/predicate/guideword>
PREFIX hazopcase: <http://www.hazop2rdf.de/hazop/subject/hazopcase/>
PREFIX hazopnode: <http://www.hazop2rdf.de/hazop/predicate/hazopnode>
PREFIX otherinfo: <http://www.hazop2rdf.de/hazop/predicate/otherinfo>
PREFIX parameter: <http://www.hazop2rdf.de/hazop/predicate/parameter>
PREFIX possibilityofavoiding: <http://www.hazop2rdf.de/hazop/predicate/possibilityofavoiding>
PREFIX probability: <http://www.hazop2rdf.de/hazop/predicate/probability>
PREFIX recommendation: <http://www.hazop2rdf.de/hazop/predicate/recommendation>
PREFIX restrisiko: <http://www.hazop2rdf.de/hazop/predicate/restrisiko>
PREFIX riskgraph: <http://www.hazop2rdf.de/hazop/predicate/riskgraph>
PREFIX safeguard: <http://www.hazop2rdf.de/hazop/predicate/safegurd>
PREFIX severity: <http://www.hazop2rdf.de/hazop/predicate/severity>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
?hazopcase
?deviation_hazopnode
?deviation_parameter
?deviation_guideword
?deviation_description
?cause_hazopnode
?cause_parameter
?cause_guideword
?cause_description
?consequence_hazopnode
?consequence_parameter
?consequence_guideword
?consequence_description
?riskgraph_severity
?riskgraph_presence
?riskgraph_avoiding
?riskgraph_probability
?safeguard_hazopnode
?safeguard_parameter
?safeguard_recommendation
?safeguard_otherinfo
?restrisiko_severity
?restrisiko_presence
?restrisiko_avoiding
?restrisiko_probability

WHERE {
    ?case deviation: ?deviation .
    ?deviation hazopnode: ?deviation_hazopnode .
    ?deviation parameter: ?deviation_parameter .
    ?deviation guideword: ?deviation_guideword .
    ?deviation description: ?deviation_description .

    ?case cause: ?cause .
    ?cause hazopnode: ?cause_hazopnode .
    ?cause parameter: ?cause_parameter .
    ?cause guideword: ?cause_guideword .
    ?cause description: ?cause_description .

    ?case consequence: ?consequence .
    ?consequence hazopnode: ?consequence_hazopnode .
    ?consequence parameter: ?consequence_parameter .
    ?consequence guideword: ?consequence_guideword .
    ?consequence description: ?consequence_description .

    ?case riskgraph: ?riskgraph .
    ?riskgraph severity: ?riskgraph_severity .
    ?riskgraph frequencyofpresence: ?riskgraph_presence .
    ?riskgraph possibilityofavoiding: ?riskgraph_avoiding .
    ?riskgraph probability: ?riskgraph_probability .

    ?case safeguard: ?safeguard .
    ?safeguard hazopnode: ?safeguard_hazopnode .
    ?safeguard parameter: ?safeguard_parameter .
    ?safeguard recommendation: ?safeguard_recommendation .
    ?safeguard otherinfo: ?safeguard_otherinfo .

    ?case restrisiko: ?restrisiko .
    ?restrisiko severity: ?restrisiko_severity .
    ?restrisiko frequencyofpresence: ?restrisiko_presence .
    ?restrisiko possibilityofavoiding: ?restrisiko_avoiding .
    ?restrisiko probability: ?restrisiko_probability .


    BIND(REPLACE(str(?case), ".*/", "") AS ?hazopcase)
}
