PREFIX blanknode: <http://www.hazop2rdf.de/hazop/blanknode/>
PREFIX hazopcase: <http://www.hazop2rdf.de/hazop/hazopcase/>
PREFIX predicate: <http://www.hazop2rdf.de/hazop/predicate/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
?hazopcase
?deviation_hazopnode
?deviation_parameter
?deviation_guideword
?deviation_description
?cause_hazopnode
?cause_parameter
?cause_guideword
?cause_description
?consequence_hazopnode
?consequence_parameter
?consequence_guideword
?consequence_description
?riskgraph_severity
?riskgraph_presence
?riskgraph_avoiding
?riskgraph_probability
?safeguard_hazopnode
?safeguard_parameter
?safeguard_recommendation
?safeguard_otherinfo
?restrisiko_severity
?restrisiko_presence
?restrisiko_avoiding
?restrisiko_probability

WHERE {
    ?case blanknode:deviation ?deviation .
    ?deviation predicate:hazopnode ?deviation_hazopnode .
    ?deviation predicate:parameter ?deviation_parameter .
    ?deviation predicate:guideword ?deviation_guideword .
    ?deviation predicate:description ?deviation_description .

    ?case blanknode:cause ?cause .
    ?cause predicate:hazopnode ?cause_hazopnode .
    ?cause predicate:parameter ?cause_parameter .
    ?cause predicate:guideword ?cause_guideword .
    ?cause predicate:description ?cause_description .

    ?case blanknode:consequence ?consequence .
    ?consequence predicate:hazopnode ?consequence_hazopnode .
    ?consequence predicate:parameter ?consequence_parameter .
    ?consequence predicate:guideword ?consequence_guideword .
    ?consequence predicate:description ?consequence_description .

    ?case blanknode:riskgraph ?riskgraph .
    ?riskgraph predicate:severity ?riskgraph_severity .
    ?riskgraph predicate:presence ?riskgraph_presence .
    ?riskgraph predicate:avoiding ?riskgraph_avoiding .
    ?riskgraph predicate:probability ?riskgraph_probability .

    ?case blanknode:safeguard ?safeguard .
    ?safeguard predicate:hazopnode ?safeguard_hazopnode .
    ?safeguard predicate:parameter ?safeguard_parameter .
    ?safeguard predicate:recommendation ?safeguard_recommendation .
    ?safeguard predicate:otherinfo ?safeguard_otherinfo .

    ?case blanknode:restrisiko ?restrisiko .
    ?restrisiko predicate:severity ?restrisiko_severity .
    ?restrisiko predicate:presence ?restrisiko_presence .
    ?restrisiko predicate:avoiding ?restrisiko_avoiding .
    ?restrisiko predicate:probability ?restrisiko_probability .

    BIND(REPLACE(str(?case), ".*/", "") AS ?hazopcase)
}