@startuml
actor User

participant "export-graphs-from\n-local-directory" as ExportFromStorage << command >>
participant "export-graphs-from\n-fuseki-server" as ExportFromFuseki << command >>

database "localhost" as Localhost << storage >>
database "Fuseki server" as Fuseki << database >>

User -> ExportFromStorage: << call >>
activate ExportFromStorage

ExportFromStorage -> Localhost: get hazop graphs
activate Localhost

Localhost --> ExportFromStorage: return hazop graphs
note left: early return if no data
deactivate Localhost

ExportFromStorage -> Localhost: save hazop graphs in excel
ExportFromStorage --> User: operation response
deactivate ExportFromStorage

User -> ExportFromFuseki: << call >>
activate ExportFromFuseki

ExportFromFuseki -> Fuseki: get hazop graphs
activate Fuseki

Fuseki --> ExportFromFuseki: return hazop graphs
note left: early return if no data
deactivate Fuseki

ExportFromFuseki -> Localhost: save hazop graphs in excel
ExportFromFuseki --> User: operation response
deactivate ExportFromFuseki
@enduml