@startuml
skinparam monochrome true
skinparam dpi 300
skinparam defaultFontSize 12

left to right direction

actor User

package HAZOP2RDF {
  usecase Importer
  usecase Exporter
}

User --> Importer
User --> Exporter
@enduml